### ISSUE TITLE
remote_state.tf.template variables not interpolated

### ISSUE THREAD

**Issue by 4x0v7** [JamesWoolfenden/terraform-azure-statebucket#5]
Hi there!

After getting the first `terraform apply` working great, doing an `init` again gets the error

```
Error: Variables not allowed

  on remote_state.tf line 3, in terraform:
   3:     resource_group_name  = resource_group_name

Variables may not be used here.


Error: Variables not allowed

  on remote_state.tf line 4, in terraform:
   4:     storage_account_name = storage_account_name

Variables may not be used here.
```

**Comment by 4x0v7** [comment]
This should be solved using interpolation syntax in the template file; `"${resource_group_name}"`, `"${storage_account_name}"`

**Comment by JamesWoolfenden** [comment]
you're not wrong, only just seen this. Thanks for logging it!

**Comment by JamesWoolfenden** [comment]
@4x0v7  if you have the time, let me know if i can close this

**Comment by JamesWoolfenden** [comment]
Verified in 0.2.3
